# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for TexLocal (v4.0.0-phase2)
#
# Build:    pyinstaller texlocal.spec
# Output:   dist/TexLocal/TexLocal.exe        (+ supporting files)
# Mode:     ONEDIR (folder of files, not single .exe).
#           Onedir is the right call for Phase 2 because:
#             * faster cold-start (no per-launch extraction)
#             * easier to debug missing-asset issues
#             * size is the same as onefile when zipped
#             * Phase 3's Inno Setup installer will package the folder anyway
#
# Run modes after build:
#   * Double-click TexLocal.exe  → app mode (PyWebView window)
#   * From terminal: `TexLocal.exe`  → same as above
#   * Source dev (`python texlocal.py` / `python texlocal_app.py`) still works
#     because nothing in texlocal.py / texlocal_app.py changed for build-time
#     other than the sys.frozen guard added in v4.0.0-phase2.

from PyInstaller.utils.hooks import collect_submodules

block_cipher = None

# ── Data files bundled into the build ─────────────────────────────────
# templates/ is the only required asset folder; everything else (CodeMirror,
# pdf.js, JetBrains Mono, Typo.js) is loaded from CDN at runtime so the
# bundle stays small.
datas = [
    ('templates', 'templates'),
    # v4.3.0 — editor CSS/JS were split out of templates/index.html into
    # static/. MUST be bundled or the frozen app serves a blank editor.
    # Flask(__name__) resolves its default static_folder relative to the
    # module's root_path, which in frozen mode is _MEIPASS; this line lands
    # static/ at _MEIPASS/static so url_for('static', ...) keeps working —
    # exactly the same mechanism that already makes templates/ work above.
    ('static', 'static'),
]

# ── Hidden imports ────────────────────────────────────────────────────
# PyInstaller's static analysis usually catches Flask/werkzeug/jinja, but
# `collect_submodules('flask')` is a cheap safety net — it picks up any
# Flask blueprint helpers that get loaded dynamically.
hiddenimports = collect_submodules('flask') + collect_submodules('werkzeug')

# ── Excludes ──────────────────────────────────────────────────────────
# Anaconda envs commonly have these installed. PyInstaller doesn't *need*
# them for TexLocal, but its dependency walker sometimes pulls them in
# transitively. Excluding shaves ~100-300MB off the build size.
excludes = [
    'tkinter',
    'matplotlib',
    'numpy',
    'scipy',
    'pandas',
    'pytest',
    'IPython',
    'jupyter',
    'notebook',
    'sphinx',
    'PIL',         # not used; if Phase 4 ever adds image processing, remove
    'sqlite3',     # Flask doesn't use it; texlocal.py doesn't either
    'tcl',
    'tk',
]

a = Analysis(
    ['texlocal_app.py'],          # entry point = the webview bootstrap
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=excludes,
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,         # onedir: binaries stay alongside, not embedded
    name='TexLocal',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,                     # UPX often trips antivirus heuristics; not worth it
    console=False,                 # no terminal popup on launch (windowed mode)
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # v4.1.3-phase3 — branded icon. Same favicon shipped inline in
    # templates/index.html and dashboard.html (blue rounded square, white
    # serif "T"). Generated by `python make_icon.py`. Multi-resolution .ico
    # so Windows picks the right size for taskbar / Start Menu / thumbnail.
    icon='texlocal.ico',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='TexLocal',               # → dist/TexLocal/
)
